### ISSUE TITLE
adversarial-review: synthesize.py reconcile_verdict_map raises raw AttributeError on non-dict verdict elements

### ISSUE THREAD

**Issue by abhattacherjee** [abhattacherjee/claude-code-skills#47]
## Problem
`reconcile_verdict_map()` in `plugins/adversarial-review/skills/adversarial-review/scripts/synthesize.py` iterates verdict elements and calls `v.get("id")` / `v.get(verdict_field)` assuming every element is a dict. A malformed verdicts file (e.g. `{"verdicts": ["C-301", 42, null]}`) raises a raw `AttributeError: 'str' object has no attribute 'get'` that propagates out of `main()` as an uncaught traceback.

## Impact
This violates the script's own clean-error contract: the file's docstring promises exit 1 = "Error (file not found, parse error, etc.)" with a tidy `Error: …` stderr message (as every other input-shape error emits), but this path dumps a Python traceback and leaks internals. The crash is loud (non-zero exit) — not a silent failure — but it is the wrong *kind* of loud: unactionable and inconsistent.

## Context
- **Pre-existing** (introduced with the #30 work, predates #31/#46). Surfaced by the silent-failure hunter during the PR #46 deep-review and correctly scoped out as a separate hardening item.
- Not reachable in any new way by #46; this is hygiene, not a regression.

## Proposed fix
Add input-shape validation in `main()` alongside the existing dict checks: verify each verdicts payload's `verdicts` key is a list whose elements are all dicts, and emit `Error: <label> 'verdicts' must be a list of verdict objects` + `sys.exit(1)` on violation. This also hardens `reconcile_verdict_map` against the same latent assumption.

## Acceptance
- A malformed verdicts file (non-list `verdicts`, or non-dict elements) exits 1 with a clean `Error: …` message, not a traceback.
- A regression test feeding a non-dict verdict element asserts the clean error + exit code.

**Comment by abhattacherjee** [comment]
### Related upstream brittleness: `gemini-review.sh` breaks on gemini-cli v0.46.0's output envelope

Surfaced while running `deep-review` Phase 2 (adversarial) on an external PR. This is the **upstream sibling** of the `synthesize.py` non-dict-verdict crash this issue tracks — same root cause class: *adversarial-review is brittle to gemini-cli's actual output shape*.

**Repro / failure mode:**
- `gemini-cli v0.46.0` (`/opt/homebrew/bin/gemini`) now wraps `-o json` output in an **outer envelope**:
  ```json
  { "session_id": "...", "response": "{\"verdicts\":[...],\"new_findings\":[...]}", "stats": {...} }
  ```
- `gemini-review.sh`'s `extract_json_object` grabs the **first** `{…}` block (the envelope), which has keys `session_id / response / stats` — **not** `verdicts / new_findings`.
- The validator then asserts `'verdicts' in data` → `AssertionError: missing verdicts key` → the script exits **3** (`ADVERSARY_UNAVAILABLE`).
- Net effect: deep-review / adversarial-review **silently degrade to Claude-only** even though Gemini is healthy and responding (it answered a 26 KB diff in ~2 s — **no hang**; the old large-stdin hang did not reproduce, so the envelope is now the blocker, not a timeout).

**Fix:** after capturing Gemini's raw stdout, unwrap one level before extracting the model JSON — parse the outer object, read the string-valued `.response`, then parse *that* as the inner JSON (strip ```json fences). I worked around it by invoking `gemini -p "<prompt>" -o json -m gemini-2.5-pro < diff` directly + this two-step parse, which recovered full cross-model confirmation.

**Suggest broadening this issue** to "harden adversarial-review against gemini-cli output-format changes": (a) `gemini-review.sh` unwrap the v0.46.0 `.response` envelope; (b) `synthesize.py` tolerate non-dict verdict elements (the original scope). Both are the same robustness gap at different stages of the pipeline.
